# Generated by Django 2.2 on 2019-05-26 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Asignatura', max_length=200)),
                ('codigo', models.CharField(help_text='Codigo de la asignatura', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', help_text='Nombre del departamento', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_text', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador unico de la pregunta', primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('question_type', models.CharField(choices=[('E', 'Encuesta'), ('T', 'Tipo Test')], default='E', max_length=1)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Asignaturas')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_docente', models.BooleanField(default=False)),
                ('is_alumno', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('despacho', models.CharField(max_length=200)),
                ('asignaturas', models.ManyToManyField(to='polls.Asignaturas')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('choice_id', models.UUIDField(default=uuid.uuid1, help_text='Identificador unico de la respuesta', primary_key=True, serialize=False)),
                ('is_correct_answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Departamento'),
        ),
    ]
