# Generated by Django 2.2 on 2019-05-22 19:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del departamento', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_text', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador unico de la pregunta', primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('question_type', models.CharField(choices=[('E', 'Encuesta'), ('T', 'Tipo Test')], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('choice_id', models.UUIDField(default=uuid.uuid1, help_text='Identificador unico de la respuesta', primary_key=True, serialize=False)),
                ('is_correct_answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Asignatura', max_length=200)),
                ('codigo', models.CharField(help_text='Codigo de la asignatura', max_length=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_docente', models.BooleanField(default=False)),
                ('nombre', models.CharField(help_text='Nombre del alumno', max_length=200)),
                ('apellido', models.CharField(help_text='Apellido del alumno', max_length=200)),
                ('asignaturas', models.ManyToManyField(to='polls.Asignaturas')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Departamento')),
            ],
        ),
    ]
