# Generated by Django 2.2 on 2019-05-28 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190527_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Departamento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='despacho',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
