# Generated by Django 2.2 on 2019-05-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190528_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='who_voted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
