# Generated by Django 2.2 on 2019-05-09 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190507_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='id',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_id',
            field=models.UUIDField(default=uuid.uuid1, help_text='Identificador unico de la respuesta', primary_key=True, serialize=False),
        ),
    ]
