# Generated by Django 2.2 on 2019-05-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_who_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='who_voted',
        ),
        migrations.AddField(
            model_name='choice',
            name='who_voted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
