# Generated by Django 2.2 on 2019-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190509_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('E', 'Encuesta'), ('T', 'Tipo Test')], default='E', max_length=1),
        ),
    ]
