# Generated by Django 2.2 on 2019-05-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
