# Generated by Django 2.2 on 2019-06-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaturas',
            name='nombre',
            field=models.TextField(help_text='Asignatura', max_length=200),
        ),
    ]
