# Generated by Django 2.2 on 2019-06-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190603_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='n_choices',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
