# Generated by Django 2.2 on 2019-06-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_question_n_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text_type_choice_text',
            field=models.TextField(blank=True, help_text='Respuesta a una pregunta', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('E', 'Encuesta'), ('T', 'Tipo Test'), ('D', 'Desarrollo')], default='E', max_length=1),
        ),
    ]
