# Generated by Django 2.2 on 2019-06-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190606_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text_type_choice_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
